title: Data Travel Guide
description: Just for fun
show_downloads: false
github:
    repository_url: https://github.com/datatravelguide/
google_analytics:
theme: jekyll-theme-hacker
google_analytics: G-WG1M2FBLH9
markdown: kramdown
kramdown:
    auto_ids: true
    toc_levels: 1..6

plugins:
  - jekyll-toc

toc:
  enabled: true
  h_min: 1
  h_max: 6
  no_toc_section_class: "no_toc"
  list_type: "ul"
  highest_h_level: 1
