title: Data Travel Guide
description: Just for fun
show_downloads: false
github:
    repository_url: https://github.com/datatravelguide/
google_analytics:
theme: jekyll-theme-hacker
google_analytics: G-WG1M2FBLH9
markdown: kramdown
kramdown:
    auto_ids: true
    toc_levels: 1..6
